name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Add environment variables to .env
      run: |
        # echo "DEBUG=0" >> .env
        # echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
        # echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        # echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        # echo " S3=False"
        # echo .env 
        echo secrets.SECRET_KEY
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Run tests
    #   run: python manage.py test